**Creación de listas desde NumPy, mediante ***array*****

In [1]:
import numpy as np #siempre se debe realizar esto para
#utilizar NumPy

In [2]:
a = np.array([1,2,3,])
print('1D array:')
print(a)
print()
b = np.array([(1,2,3),(4,5,6)])
print('2D array:')
print(b)

1D array:
[1 2 3]

2D array:
[[1 2 3]
 [4 5 6]]


<hr>

**A continuación se demuestra, mediante arange, la cantidad de memoria utilizada por una Lista de Python normal y una array de NumPy**

In [3]:
import sys
S = range(1000)
print('Resultado lista de Python:')
print(sys.getsizeof(5)*len(S))
print()
D = np.arange(1000) #arange es el resultado de la cantidad de memoria a utilizar
print('Resultado NumPy array:')
print(D.size*D.itemsize)

Resultado lista de Python:
28000

Resultado NumPy array:
8000


<hr>

**A continuación se muestran la diferencia de velocidad entre la creación de una Lista mediante lo normal de Python, y realizarlo desde NumPy, que es mucho más rápido.***

In [7]:
import time

SIZE = 1000000
L1 = range(SIZE)
L2 = range(SIZE)
A1 = np.arange(SIZE)
A2 = np.arange(SIZE)

start = time.time()
result = [(x,y) for x,y in zip(L1,L2)]
print('Resultado lista de Python:')
print((time.time()-start)*1000)
print()
start=time.time()
result=A1+A2
print('Resultado NumPy array:')
print((time.time()-start)*1000)

Resultado lista de Python:
202.98027992248535

Resultado NumPy array:
70.65391540527344


<hr>

**Crear una matriz de:**

In [9]:
#solamente 1s
unos = np.ones((3,4)) #en este caso 3 filas y 4 columnas
print(unos)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [10]:
#solamente 0s
ceros = np.zeros((3,4)) #en este caso 3 filas y 4 columnas
print(ceros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [13]:
#numeros aleatorios
aleatorios = np.random.random((2,2))
print(aleatorios)

[[0.12280101 0.41890929]
 [0.9401809  0.8291131 ]]


In [14]:
#vacía
vacia = np.empty((3,2))
print(vacia)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [15]:
#Con un solo valor
full = np.full((2,2),8) #se crearan solamente 8s
print(full)

[[8 8]
 [8 8]]


In [16]:
#Con valores espaciados uniformemente
espacio1 = np.arange(0,30,5)#espacio de 5 entre números
print(espacio1)
print()
espacio2 = np.linspace(0,2,5)#5 valores entre 0 y 2
print(espacio2)

[ 0  5 10 15 20 25]

[0.  0.5 1.  1.5 2. ]


In [17]:
#Matríz identidad
identidad1 = np.eye(4,4)
print(identidad1)
print()
identidad2 = np.identity(4)
print(identidad2)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


<hr>

**Inspecciona Matrices**

In [19]:
#Conocer las dimensiones de una matriz
a = np.array([(1,2,3),(4,5,6)])
print(a.ndim) #ndim para dimension

2


In [22]:
#conocer los tipos de datos junto con el tamaño
a = np.array([(1,2,3)])
print(a.dtype)

int64


In [23]:
#Conocer el tamaño y forma de la matriz
a = np.array([(1,2,3,4,5,6)])
print(a.size) #tamaño
print(a.shape) #forma

6
(1, 6)


<hr>

**Cambio de tamaño y forma de las matrices**

In [24]:
a = np.array([(8,9,10),(11,12,13)])
print(a)
print()
a=a.reshape(3,2) #aquí se realiza el enroque
print(a)

[[ 8  9 10]
 [11 12 13]]

[[ 8  9]
 [10 11]
 [12 13]]


In [39]:
#seleccionar 1 elemento de la matriz
a = np.array([(1,2,3,4),(3,4,5,6)])
print(a)
print()
print(a[0,2]) #ubicado en fila 0, columna 2
print()
print(a[0:,2]) #tener todos los elementos de todas las filas de columna 2

[[1 2 3 4]
 [3 4 5 6]]

3

[3 5]


<hr>

**Operaciones matemáticas entre matrices**

In [40]:
#encontrar el mínimo, máximo y la suma
a = np.array([2,4,8])
print(a.min())
print(a.max())
print(a.sum())

2
8
14


In [42]:
#Calcular raíz cuadrada y la desviación estándar
a = np.array([(1,2,3),(3,4,5)])
print(np.sqrt(a))
print()
print(np.std(a))

[[1.         1.41421356 1.73205081]
 [1.73205081 2.         2.23606798]]

1.2909944487358056


In [43]:
#Suma, resta, mutiplicacion y división entre 2 matrices
x = np.array([(1,2,3),(3,4,5)])
y = np.array([(1,2,3),(3,4,5)])
print(x+y)
print()
print(x-y)
print()
print(x*y)
print()
print(x/y)

[[ 2  4  6]
 [ 6  8 10]]

[[0 0 0]
 [0 0 0]]

[[ 1  4  9]
 [ 9 16 25]]

[[1. 1. 1.]
 [1. 1. 1.]]


En la pagina web de la librería NumPy, aparecen todas las funciones con sus detalles